#!/bin/sh
#!/bin/sh

#
# This script is run inside of the initramfs environment during the
# system boot process.  It is installed there by 'update-initramfs'.
# The # package that owns it may opt to install it in an appropriate
# location under "/usr/share/initramfs-tools/scripts/".
#
# see initramfs-tools(8) for more details.

#
# List the soft prerequisites here.  This is a space separated list of
# names, of scripts that are in the same directory as this one, that
# must be run before this one can be.
#
PREREQ="lvm"

prereqs()
{
        echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
        prereqs
        exit 0
        ;;
esac

. /scripts/functions
# Do the work here.
if [ -x /sbin/lvm ]; then
    log_begin_msg "Activating volume groups"
    /sbin/lvm vgchange -aly
    log_end_msg
fi

echo "Done activating volume groups!"

exit 0
